name: standalone_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test:
  build_runner:
  build_test: ^1.3.0
  build_web_compilers: ^2.12.0
  envify_generator:
  http:

dependencies:
  crypto:
  dart_jsonwebtoken:
  shelf:
  envify:
  shelf_router:
  shelf_static:
