name: standalone_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test:
  http:

dependencies:
  dart_jsonwebtoken:
  shelf:
  shelf_router:
  shelf_static:
